# Generated by Django 5.1.7 on 2025-03-10 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=120, null=True, unique=True)),
                ('email', models.CharField(max_length=150, null=True, unique=True)),
                ('password', models.CharField(max_length=120)),
                ('confirm_pasword', models.CharField(max_length=120)),
            ],
        ),
    ]
