# Generated by Django 5.1.7 on 2025-03-12 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup_login', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='confirm_pasword',
            new_name='confirm_password',
        ),
    ]
