# Generated by Django 5.1.7 on 2025-03-12 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup_login', '0003_alter_user_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='confirm_password',
            new_name='Confirm_password',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='email',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='password',
            new_name='Password',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='Username',
        ),
    ]
