# Generated by Django 5.1.7 on 2025-03-12 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup_login', '0005_rename_confirm_password_user_confirm_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='confirm_password',
        ),
    ]
